// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.1

package helloworld

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type HelloworldHTTPServer interface {
	ListHelloworld(context.Context, *ListHelloworldRequest) (*ListHelloworldReply, error)
}

func RegisterHelloworldHTTPServer(s *http.Server, srv HelloworldHTTPServer) {
	r := s.Route("/")
	r.GET("/helloworld2/{name}", _Helloworld_ListHelloworld0_HTTP_Handler(srv))
}

func _Helloworld_ListHelloworld0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHelloworldRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.helloworld.Helloworld/ListHelloworld")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHelloworld(ctx, req.(*ListHelloworldRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHelloworldReply)
		return ctx.Result(200, reply)
	}
}

type HelloworldHTTPClient interface {
	ListHelloworld(ctx context.Context, req *ListHelloworldRequest, opts ...http.CallOption) (rsp *ListHelloworldReply, err error)
}

type HelloworldHTTPClientImpl struct {
	cc *http.Client
}

func NewHelloworldHTTPClient(client *http.Client) HelloworldHTTPClient {
	return &HelloworldHTTPClientImpl{client}
}

func (c *HelloworldHTTPClientImpl) ListHelloworld(ctx context.Context, in *ListHelloworldRequest, opts ...http.CallOption) (*ListHelloworldReply, error) {
	var out ListHelloworldReply
	pattern := "/helloworld2/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.helloworld.Helloworld/ListHelloworld"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
